import {
  VIRTUAL_WIDTH, VIRTUAL_HEIGHT, WORLD_SCALE, TENSE_KEYS,
  PLAYER_DEATH_DELAY_SECONDS, BOSS_TRIALS_REQUIRED,
  BOSS_TRIAL_TIME_LIMIT_SECONDS,
} from "./constants.js";
import { createRunSeed } from "./utils.js";
import { getStartingHearts } from "./constants.js";

// ─── Canvas ───
export const canvas = document.getElementById("gameCanvas");
export const ctx = canvas.getContext("2d");
ctx.imageSmoothingEnabled = false;
canvas.width = VIRTUAL_WIDTH;
canvas.height = VIRTUAL_HEIGHT;

// ─── DOM element refs ───
export const ui = {
  hudScoreValue: document.getElementById("hudScoreValue"),
  cheatModal: document.getElementById("cheatModal"),
  cheatLevelSelect: document.getElementById("cheatLevelSelect"),
  cheatHeroSelect: document.getElementById("cheatHeroSelect"),
  cheatGivePiecesBtn: document.getElementById("cheatGivePiecesBtn"),
  cheatApplyBtn: document.getElementById("cheatApplyBtn"),
  cheatCloseBtn: document.getElementById("cheatCloseBtn"),
  cheatWorldZoomSlider: document.getElementById("cheatWorldZoomSlider"),
  cheatWorldZoomValue: document.getElementById("cheatWorldZoomValue"),
  visualDebugPanel: document.getElementById("visualDebugPanel"),
  debugButtonsOffsetSlider: document.getElementById("debugButtonsOffsetSlider"),
  debugButtonsOffsetValue: document.getElementById("debugButtonsOffsetValue"),
  debugGameOffsetSlider: document.getElementById("debugGameOffsetSlider"),
  debugGameOffsetValue: document.getElementById("debugGameOffsetValue"),
  debugScaleSlider: document.getElementById("debugScaleSlider"),
  debugScaleValue: document.getElementById("debugScaleValue"),
  validateLevelsBtn: document.getElementById("validateLevelsBtn"),
  validateLevelsOutput: document.getElementById("validateLevelsOutput"),
  closeVisualDebugBtn: document.getElementById("closeVisualDebugBtn"),
  hudLives: document.getElementById("hudLives"),
  hudGoldValue: document.getElementById("hudGoldValue"),
  shopBtn: document.getElementById("shopBtn"),
  shopIcon: document.getElementById("shopIcon"),
  pauseBtn: document.getElementById("pauseBtn"),
  pauseIcon: document.getElementById("pauseIcon"),
  settingsPanel: document.getElementById("settingsPanel"),
  shopPanel: document.getElementById("shopPanel"),
  heroSelect: document.getElementById("heroSelect"),
  heroShopList: document.getElementById("heroShopList"),
  shopGoldValue: document.getElementById("shopGoldValue"),
  levelSelect: document.getElementById("levelSelect"),
  difficultySelect: document.getElementById("difficultySelect"),
  tileStyleSelect: document.getElementById("tileStyleSelect"),
  worldZoomSlider: document.getElementById("worldZoomSlider"),
  worldZoomValue: document.getElementById("worldZoomValue"),
  questionPanel: document.getElementById("questionPanel"),
  questionEnemy: document.getElementById("questionEnemy"),
  questionGroup: document.getElementById("questionGroup"),
  questionTense: document.getElementById("questionTense"),
  questionCountdown: document.getElementById("questionCountdown"),
  questionPrompt: document.getElementById("questionPrompt"),
  answerButtons: document.getElementById("answerButtons"),
  groupFilters: document.getElementById("groupFilters"),
  tenseFilters: document.getElementById("tenseFilters"),
  resetErrorsBtn: document.getElementById("resetErrorsBtn"),
  errorList: document.getElementById("errorList"),
  applySettingsBtn: document.getElementById("applySettingsBtn"),
  closeSettingsBtn: document.getElementById("closeSettingsBtn"),
  closeShopBtn: document.getElementById("closeShopBtn"),
  moveLeftBtn: document.getElementById("moveLeftBtn"),
  moveRightBtn: document.getElementById("moveRightBtn"),
  jumpBtn: document.getElementById("jumpBtn"),
  castFireBtn: document.getElementById("castFireBtn"),
  moveLeftHitBtn: document.getElementById("moveLeftHitBtn"),
  moveRightHitBtn: document.getElementById("moveRightHitBtn"),
  jumpHitBtn: document.getElementById("jumpHitBtn"),
  castFireHitBtn: document.getElementById("castFireHitBtn"),
  btnLeft: document.getElementById("btnLeft"),
  btnRight: document.getElementById("btnRight"),
  btnUp: document.getElementById("btnUp"),
  btnFire: document.getElementById("btnFire"),
  titleScreen: document.getElementById("titleScreen"),
  startBtn: document.getElementById("startBtn"),
  openSettingsFromTitleBtn: document.getElementById("openSettingsFromTitleBtn"),
  pauseModal: document.getElementById("pauseModal"),
  resumeBtn: document.getElementById("resumeBtn"),
  openSettingsFromPauseBtn: document.getElementById("openSettingsFromPauseBtn"),
  backToTitleBtn: document.getElementById("backToTitleBtn"),
  gameOverPanel: document.getElementById("gameOverPanel"),
  gameOverTitle: document.getElementById("gameOverTitle"),
  gameOverText: document.getElementById("gameOverText"),
  finalScoreText: document.getElementById("finalScoreText"),
  finalCoinsText: document.getElementById("finalCoinsText"),
  restartBtn: document.getElementById("restartBtn"),
  backToTitleFromGameOverBtn: document.getElementById("backToTitleFromGameOverBtn"),
  bossDefeatPanel: document.getElementById("bossDefeatPanel"),
  bossDefeatText: document.getElementById("bossDefeatText"),
  bossDefeatRetryText: document.getElementById("bossDefeatRetryText"),
  finalVictoryPanel: document.getElementById("finalVictoryPanel"),
  backToTitleFromVictoryBtn: document.getElementById("backToTitleFromVictoryBtn"),
};

// ─── Image caches ───
export const imageCache = new Map();
export const imagePromiseCache = new Map();
export const spriteBoundsCache = new WeakMap();
export const tileVerticalCollisionInsetCache = new Map();
export const spriteBoundsCanvas = document.createElement("canvas");
export const spriteBoundsCtx = spriteBoundsCanvas.getContext("2d", { willReadFrequently: true });

// ─── Game state ───
export const state = {
  ready: false,
  started: false,
  paused: false,
  gameOver: false,
  config: null,
  tileSize: 64,
  biomes: {},
  heroes: [],
  enemies: [],
  levels: [],
  levelSeedBase: createRunSeed(),
  heroUnlocks: {},
  selectedHeroIndex: 0,
  pendingBossStart: false,
  currentLevelIndex: 0,
  currentLevel: null,
  player: null,
  cameraX: 0,
  controls: {
    left: false,
    right: false,
    jumpBuffered: false,
    jumpHeld: false,
    jumpBufferTime: 0,
  },
  fireballs: [],
  runTime: 0,
  score: 0,
  coins: 0,
  persistentGold: 0,
  hearts: getStartingHearts("normal"),
  cheatLongPressTimer: null,
  visualDebugLongPressTimer: null,
  visualDebugOpen: false,
  mobileButtonsOffsetY: 140,
  mobileGameOffsetY: -150,
  generationProfile: "normal",
  tileStyleMode: "new",
  worldZoom: WORLD_SCALE,
  screenMode: "game",
  pedagogy: {
    activeGroups: [],
    activeTenses: TENSE_KEYS.slice(),
  },
  duel: null,
  message: "",
  messageUntil: 0,
  endCastleLockHintUntil: 0,
  playerHitInvuln: 0,
  playerHitStun: 0,
  deathSequence: {
    active: false,
    elapsed: 0,
    duration: PLAYER_DEATH_DELAY_SECONDS,
  },
  respawnTrail: {
    elapsedSinceSample: 0,
    history: [],
  },
  lastTimestamp: 0,
  towerInterior: {
    active: false,
    outsideX: 0,
    outsideY: 0,
    chestState: "locked",
    chestStreak: 0,
    chestRequired: 3,
    chestRewardPieces: 0,
    chestExplodeUntil: 0,
    chestPromptUntil: 0,
  },
  boss: {
    active: false,
    phase: "idle",
    streak: 0,
    required: BOSS_TRIALS_REQUIRED,
    trialDeadline: 0,
    trialTimeLimit: BOSS_TRIAL_TIME_LIMIT_SECONDS,
    phaseUntil: 0,
    defeatReason: "",
    sourceLevelIndex: 0,
    introUntil: 0,
    introMessageVisible: false,
  },
};
