// ─── Japanese verb conjugation bank ───
// Structure mirrors French verb source: { group: { label, list: { verbKey: { inf, form: [conjugation] } } } }
// Japanese verbs don't conjugate by person, so each form array has a single element (index 0).

export const JA_FORM_LABEL = {
  masu:   "ます形 (Poli)",
  te:     "て形",
  ta:     "た形 (Passé)",
  nai:    "ない形 (Négatif)",
  kanou:  "可能形 (Potentiel)",
  meirei: "命令形 (Impératif)",
};

export const JA_FORM_KEYS = Object.keys(JA_FORM_LABEL);

export const JA_JLPT_PRESETS = {
  n5: {
    forms: ["masu", "te", "ta", "nai"],
    groups: ["ichidan", "godan", "irregular"],
    label: "JLPT N5",
  },
  n4: {
    forms: ["masu", "te", "ta", "nai", "kanou"],
    groups: ["ichidan", "godan", "irregular"],
    label: "JLPT N4",
  },
  n3: {
    forms: ["masu", "te", "ta", "nai", "kanou", "meirei"],
    groups: ["ichidan", "godan", "irregular"],
    label: "JLPT N3",
  },
};

export function getJapaneseVerbSource() {
  return {
    ichidan: {
      label: "一段動詞 (Ichidan)",
      list: {
        taberu: {
          inf: "食べる",
          masu:   ["食べます"],
          te:     ["食べて"],
          ta:     ["食べた"],
          nai:    ["食べない"],
          kanou:  ["食べられる"],
          meirei: ["食べろ"],
        },
        miru: {
          inf: "見る",
          masu:   ["見ます"],
          te:     ["見て"],
          ta:     ["見た"],
          nai:    ["見ない"],
          kanou:  ["見られる"],
          meirei: ["見ろ"],
        },
        neru: {
          inf: "寝る",
          masu:   ["寝ます"],
          te:     ["寝て"],
          ta:     ["寝た"],
          nai:    ["寝ない"],
          kanou:  ["寝られる"],
          meirei: ["寝ろ"],
        },
        okiru: {
          inf: "起きる",
          masu:   ["起きます"],
          te:     ["起きて"],
          ta:     ["起きた"],
          nai:    ["起きない"],
          kanou:  ["起きられる"],
          meirei: ["起きろ"],
        },
        deru: {
          inf: "出る",
          masu:   ["出ます"],
          te:     ["出て"],
          ta:     ["出た"],
          nai:    ["出ない"],
          kanou:  ["出られる"],
          meirei: ["出ろ"],
        },
        ireru: {
          inf: "入れる",
          masu:   ["入れます"],
          te:     ["入れて"],
          ta:     ["入れた"],
          nai:    ["入れない"],
          kanou:  ["入れられる"],
          meirei: ["入れろ"],
        },
        oshieru: {
          inf: "教える",
          masu:   ["教えます"],
          te:     ["教えて"],
          ta:     ["教えた"],
          nai:    ["教えない"],
          kanou:  ["教えられる"],
          meirei: ["教えろ"],
        },
        kangaeru: {
          inf: "考える",
          masu:   ["考えます"],
          te:     ["考えて"],
          ta:     ["考えた"],
          nai:    ["考えない"],
          kanou:  ["考えられる"],
          meirei: ["考えろ"],
        },
        akeru: {
          inf: "開ける",
          masu:   ["開けます"],
          te:     ["開けて"],
          ta:     ["開けた"],
          nai:    ["開けない"],
          kanou:  ["開けられる"],
          meirei: ["開けろ"],
        },
        shimeru: {
          inf: "閉める",
          masu:   ["閉めます"],
          te:     ["閉めて"],
          ta:     ["閉めた"],
          nai:    ["閉めない"],
          kanou:  ["閉められる"],
          meirei: ["閉めろ"],
        },
        tsukeru: {
          inf: "つける",
          masu:   ["つけます"],
          te:     ["つけて"],
          ta:     ["つけた"],
          nai:    ["つけない"],
          kanou:  ["つけられる"],
          meirei: ["つけろ"],
        },
        wasureru: {
          inf: "忘れる",
          masu:   ["忘れます"],
          te:     ["忘れて"],
          ta:     ["忘れた"],
          nai:    ["忘れない"],
          kanou:  ["忘れられる"],
          meirei: ["忘れろ"],
        },
      },
    },
    godan: {
      label: "五段動詞 (Godan)",
      list: {
        kaku: {
          inf: "書く",
          masu:   ["書きます"],
          te:     ["書いて"],
          ta:     ["書いた"],
          nai:    ["書かない"],
          kanou:  ["書ける"],
          meirei: ["書け"],
        },
        yomu: {
          inf: "読む",
          masu:   ["読みます"],
          te:     ["読んで"],
          ta:     ["読んだ"],
          nai:    ["読まない"],
          kanou:  ["読める"],
          meirei: ["読め"],
        },
        nomu: {
          inf: "飲む",
          masu:   ["飲みます"],
          te:     ["飲んで"],
          ta:     ["飲んだ"],
          nai:    ["飲まない"],
          kanou:  ["飲める"],
          meirei: ["飲め"],
        },
        hanasu: {
          inf: "話す",
          masu:   ["話します"],
          te:     ["話して"],
          ta:     ["話した"],
          nai:    ["話さない"],
          kanou:  ["話せる"],
          meirei: ["話せ"],
        },
        kiku: {
          inf: "聞く",
          masu:   ["聞きます"],
          te:     ["聞いて"],
          ta:     ["聞いた"],
          nai:    ["聞かない"],
          kanou:  ["聞ける"],
          meirei: ["聞け"],
        },
        matsu: {
          inf: "待つ",
          masu:   ["待ちます"],
          te:     ["待って"],
          ta:     ["待った"],
          nai:    ["待たない"],
          kanou:  ["待てる"],
          meirei: ["待て"],
        },
        kaeru: {
          inf: "帰る",
          masu:   ["帰ります"],
          te:     ["帰って"],
          ta:     ["帰った"],
          nai:    ["帰らない"],
          kanou:  ["帰れる"],
          meirei: ["帰れ"],
        },
        aruku: {
          inf: "歩く",
          masu:   ["歩きます"],
          te:     ["歩いて"],
          ta:     ["歩いた"],
          nai:    ["歩かない"],
          kanou:  ["歩ける"],
          meirei: ["歩け"],
        },
        au: {
          inf: "会う",
          masu:   ["会います"],
          te:     ["会って"],
          ta:     ["会った"],
          nai:    ["会わない"],
          kanou:  ["会える"],
          meirei: ["会え"],
        },
        kau: {
          inf: "買う",
          masu:   ["買います"],
          te:     ["買って"],
          ta:     ["買った"],
          nai:    ["買わない"],
          kanou:  ["買える"],
          meirei: ["買え"],
        },
        tsukau: {
          inf: "使う",
          masu:   ["使います"],
          te:     ["使って"],
          ta:     ["使った"],
          nai:    ["使わない"],
          kanou:  ["使える"],
          meirei: ["使え"],
        },
        omou: {
          inf: "思う",
          masu:   ["思います"],
          te:     ["思って"],
          ta:     ["思った"],
          nai:    ["思わない"],
          kanou:  ["思える"],
          meirei: ["思え"],
        },
        shiru: {
          inf: "知る",
          masu:   ["知ります"],
          te:     ["知って"],
          ta:     ["知った"],
          nai:    ["知らない"],
          kanou:  ["知れる"],
          meirei: ["知れ"],
        },
        motsu: {
          inf: "持つ",
          masu:   ["持ちます"],
          te:     ["持って"],
          ta:     ["持った"],
          nai:    ["持たない"],
          kanou:  ["持てる"],
          meirei: ["持て"],
        },
        asobu: {
          inf: "遊ぶ",
          masu:   ["遊びます"],
          te:     ["遊んで"],
          ta:     ["遊んだ"],
          nai:    ["遊ばない"],
          kanou:  ["遊べる"],
          meirei: ["遊べ"],
        },
        oyogu: {
          inf: "泳ぐ",
          masu:   ["泳ぎます"],
          te:     ["泳いで"],
          ta:     ["泳いだ"],
          nai:    ["泳がない"],
          kanou:  ["泳げる"],
          meirei: ["泳げ"],
        },
        tatsu: {
          inf: "立つ",
          masu:   ["立ちます"],
          te:     ["立って"],
          ta:     ["立った"],
          nai:    ["立たない"],
          kanou:  ["立てる"],
          meirei: ["立て"],
        },
        shinu: {
          inf: "死ぬ",
          masu:   ["死にます"],
          te:     ["死んで"],
          ta:     ["死んだ"],
          nai:    ["死なない"],
          kanou:  ["死ねる"],
          meirei: ["死ね"],
        },
      },
    },
    irregular: {
      label: "不規則動詞 (Irréguliers)",
      list: {
        suru: {
          inf: "する",
          masu:   ["します"],
          te:     ["して"],
          ta:     ["した"],
          nai:    ["しない"],
          kanou:  ["できる"],
          meirei: ["しろ"],
        },
        kuru: {
          inf: "来る",
          masu:   ["来ます"],
          te:     ["来て"],
          ta:     ["来た"],
          nai:    ["来ない"],
          kanou:  ["来られる"],
          meirei: ["来い"],
        },
      },
    },
  };
}
